apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo-app
type: Opaque
data:
  mysql-root-password: cm9vdA==        # base64 for "root"
  mysql-user: dXNlcg==                 # "user"
  mysql-password: cGFzc3dvcmQ=         # "password"
