apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulndemo
  namespace: demo-app
  labels:
    app: vulndemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vulndemo
  template:
    metadata:
      labels:
        app: vulndemo
    spec:
      containers:
      - name: vulndemo
        image: us-central1-docker.pkg.dev/PROJECT_ID/app-repo/vulndemo:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql.demo-app.svc.cluster.local:3306/vulndb
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
