name: Guardrails demo

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: install snyk to html
        run: npm install snyk-to-html -g
        
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects --sarif-file-output=.github/snyk.sarif

      - name: Run Snyk to check for vulnerabilities and generate Html report
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --json | snyk-to-html -o results-opensource.html
          
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk monitor --all-projects

      - name: Build the Docker image
        run: docker build -t vulndemo:1.0 .

      - name: Run Snyk Container Scan
        continue-on-error: true
        run: snyk container test vulndemo:1.0 --file=Dockerfile

      - name: Upload Container Scan Results to Snyk Dashboard
        continue-on-error: true
        run: snyk container monitor vulndemo:1.0 --file=Dockerfile